targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            "lib/data/entities/{{}}.dart": "lib/data/entities/generated/{{}}.g.dart"
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/data/entities/{{}}.dart': 'lib/data/entities/generated/{{}}.freezed.dart'
            'lib/{{}}.dart': 'lib/{{}}.freezed.dart'