name: test_task
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  get_it: ^8.0.0
  http: ^1.2.2
  hive: ^2.2.3
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - lib/core/localization/
