name: test_task
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  get_it: ^8.0.0
  http: ^1.2.2
  hive: ^2.2.3
  easy_localization: ^3.0.7
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  dart_define: ^2.1.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - lib/core/localization/


dart_define:
    dart: true
    json: true

    dart_path: lib/core/config/dart_define.gen.dart
    json_path: dart_define.json
    class_name: dart_define

    variables:

        - name: OPENWEATHER_KEY

          description: Open Weather API key

          required: true

        - name: GEONAMES_USERNAME

          description: Geonames username

          required: true