// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();
  
  /// Open Weather API key
  static const openweatherKey = String.fromEnvironment('OPENWEATHER_KEY');

  /// Geonames username
  static const geonamesUsername = String.fromEnvironment('GEONAMES_USERNAME');
}

    